# Site settings
title: Alliv Blog
tagline: Under Construction
email: prostoalex333@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, Iâ€™m a professional programmer. 
  I work mainly on PC and dream of creating one 
  great computer game. 
baseurl: "gaya" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ALivshitz
github_username:  alxliv
logourl: /assets/images/logo.png # Site logo
author: "Alex"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!

# Build settings
markdown: kramdown

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude:
  - Gemfile
  - Gemfile.lock

theme: minima

gems: 
  - jekyll-paginate
  - jekyll-feed