# Site settings
title: Alliv Blog
tagline: Under Construction
email: prostoalex333@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I program computers.
  I work mainly on PC and dream of creating one 
  great game. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alxliv.github.io/gaya/" # the base hostname & protocol for your site
logourl: "assets/images/logo.png" # Site logo
author: "Alex"
author_thumbnail: "assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

gems: [jekyll-paginate]
